### ISSUE TITLE
"Hide" secret recovery phrase when the user is typing it in

### ISSUE THREAD

**Issue by jaa2** [jaa2/ethereum-web-wallet#14]
The secret recovery phrase should be less visible (maybe a color very close to the background of the screen) so that the user does not mistaken the task to mean copying the phrase already on the screen.

- [x] Change the color of the secret recovery phrase text as long as the user has entered text into the entry field
- [x] If the trimmed entered text is empty, show the original text color again
- [x] Prevent user from selecting text

**Comment by chbkull** [comment]
On preventing user selection:

https://stackoverflow.com/a/63652442
