### ISSUE TITLE
Open in New Tab Button

### ISSUE THREAD

**Issue by jaa2** [jaa2/ethereum-web-wallet#55]
The pop-up window (when not already in a new tab) must have an "open in new tab" button that moves the view from the pop-up into a new tab. This button should be immediately accessible from the Home screen and other screens that follow a similar style.

Opening our extension's pages in a new tab will make it easier for people to see everything on the simulation page.

- [x] Add some sort of "open in new tab" button to the Home page (it doesn't exactly have to be named that, but the button's purpose should be obvious)
- [x] Hide this button when the view is already opened in a new tab

**Comment by jaa2** [comment]
One possible way to distinguish the pop-up page from the new tab view is to make the new tab view an entirely different page altogether, with the same JSX root element ("App") as the pop-up. This new page could import CSS that is different from the pop-up in order to have a new style.

**Comment by chbkull** [comment]
Completed, sitting in branch chris_dev while working on other tasks.
