### ISSUE TITLE
Realtime USD calculation on Send Transaction page

### ISSUE THREAD

**Issue by jaa2** [jaa2/ethereum-web-wallet#56]
Users do not yet see the USD conversion of their ETH on the Send Transaction page. The conversion from ETH to USD should be found once and then updated in realtime as the user types the ETH amount into the input field.

- [x] Find the ETH to USD conversion rate on page load (this is found on the homepage, so maybe we should cache the conversion rate)
- [x] Update the value in realtime as the user types the ETH amount

**Comment by kaikaiy17** [comment]
Did the conversion in a more taxing way, so probably need to change some time soon.

**Comment by jaa2** [comment]
You should be able to do this by finding the conversion rate on page load and storing it in a state variable

**Comment by kaikaiy17** [comment]
Loaded in the state the same exact way as the home page to get the conversion rate
