### ISSUE TITLE
Truncate recent activity

### ISSUE THREAD

**Issue by jaa2** [jaa2/ethereum-web-wallet#58]
Currently, the recent activity list can span to include well over 100 transactions. Because our wallet is not a block explorer, we should limit the recent activity to include only 10 or 20 of the last transactions and direct users to a block explorer if they want to view older ones.

- [x] Truncate recent activity to either the last 10 or 20 transactions

**Comment by chbkull** [comment]
Completed, sitting in branch chris_dev while working on other tasks.
