### ISSUE TITLE
Respond to blockchain events in the Home page (like when a transaction is included in a block)

### ISSUE THREAD

**Issue by jaa2** [jaa2/ethereum-web-wallet#60]
Transactions on the Home page should respond to blockchain events as they happen.

- [x] Convert a "pending" transaction to an "included" transaction once a transaction has been included in a block
  - [x] Remove Cancel and Replace buttons in that case

**Comment by kaikaiy17** [comment]
Second task was already covered

**Comment by kaikaiy17** [comment]
Already covered
