### ISSUE TITLE
Send and Test Transaction error handling

### ISSUE THREAD

**Issue by jaa2** [jaa2/ethereum-web-wallet#66]
It's possible that transactions we create are not able to be broadcast to the network. This might be because of a provider connection issue or a transaction whose intrinsic gas is too low (e.g. a gas limit < 21,000). We must inform the user if this happens and allow the user to re-send the transaction.

- [x] Catch any errors that occur when sending a transaction
- [x] Display the error message, including the reason the transaction failed to send, to the user in a non-intrusive form (i.e. not a pop-up or alert dialog)
- [x] Re-enable the send transaction button so that the user can try again (especially important if, for instance, it was a network connection problem)

**Comment by kaikaiy17** [comment]
Apply to test transaction button as well

**Comment by kaikaiy17** [comment]
Test transaction error handling has been completed; however, toast associated with clicking on the test transaction button needs to be cleaned up. Shortening error messages into informative pieces, smoothening hiding of toasts, and better placing the toast

**Comment by kaikaiy17** [comment]
Send transaction button error handling implemented similarly to test transaction error handling; however, just like the previous error handling it requires polishing
