### ISSUE TITLE
Prevent duplicate transactions in transaction history and assign the "SELF" label

### ISSUE THREAD

**Issue by jaa2** [jaa2/ethereum-web-wallet#67]
Etherscan's `getHistory` API call returns transactions twice when the sender and destination address are the same.

- [x] Prevent duplicate transactions from appearing in the transaction history on the home page. Two transactions are the same if they have the same transaction hash.
- [x] If a transaction's `from` address is the same as its `to` address, instead of assigning it a label of "IN" or "OUT", assign it a label of "SELF" to indicate that it is a self-transaction.

**Comment by chbkull** [comment]
Also clean up the two appearances of the function into one.

**Comment by chbkull** [comment]
Remove boostrap :)

**Comment by chbkull** [comment]
Completed, sitting in branch chris_dev while working on other tasks.
