### ISSUE TITLE
Numbers with a leading decimal are not accepted/invalid numbers are accepted

### ISSUE THREAD

**Issue by jaa2** [jaa2/ethereum-web-wallet#71]
User input values are being flagged as invalid if they have a leading decimal character when they should be accepted:

![image](https://user-images.githubusercontent.com/43010335/143972060-f6ef9a03-aae0-49a3-814f-683218dfeb7a.png)

We MUST use the `ethers.utils.parseEther` function or `ethers.utils.parseUnits(val, 9)` for gwei rather than some sort of regex because we cannot accept input that is longer than the number of decimal places we have, which is also a problem:

![image](https://user-images.githubusercontent.com/43010335/143972628-da3e3cd0-07d2-42b4-9f13-25733769d3dc.png)

This number has 19 decimal places and will silently throw an error after the user clicks the Test Transaction button.

- [x] Use `ethers.utils.parseEther` to parse all Ether input values
- [x] Use `ethers.utils.parseUnits` when parsing values that have other numbers of decimal places (e.g., 9 for gwei)

**Comment by kaikaiy17** [comment]
Added regex back in to prevent leadings zeros. With only ethers.utils.parseEther(), the implementation allows 01, 00001234, etc. Regex essentially does the initial checks to make sure the number is valid in which something on the lines of .28 is allowed. Error on ethers.utils.parseEther() for numbers with 19 or more decimal places will be caught appropriately by a catch statement

**Comment by jaa2** [comment]
Good catch! That seems reasonable.
