### ISSUE TITLE
Link to block explorer for full transaction history.

### ISSUE THREAD

**Issue by chbkull** [jaa2/ethereum-web-wallet#79]
The recent activity list will now be limited to the last 10 transactions associated with the user's address. On the off chance that they would want to view past that, it would be convenient to link them to a block explorer to see the full address history. Etherscan is perfect here, only hitch would be dynamically changing the link if network switching is implemented in the future.

- [x] Add some sort of "view full history" button to the Home page, somewhere close to the transaction history
- [x] Dynamically update the URL to reflect the selected network, if applicable

**Comment by jaa2** [comment]
Resolved by 632e6bb
